Example_Item:
  Name: "&bExample item"
  Material: "STONE"
  Amount: 1
  glow: false #Not implemented yet!
  lore:
    - "&cExample&b&n lore :0"
superPickaxe:
  Name: "&4&k!!!&r &d&nSuper Pickaxe &4&k!!!!&r"
  Material: "DIAMOND_PICKAXE"
  Amount: 1
  glow: false #Not implemented yet!
  lore:
    - "&cSuper pickaxe what did you expect!"